-- =====================================================
-- FORTNITE SPRITE TRACKER DATABASE
-- INITIAL SCHEMA
-- =====================================================

create table seasons (
    id bigint generated by default as identity primary key,

    season_key text not null unique,
    chapter integer not null,
    season integer not null,
    name text not null,

    game_version text,
    date_begin timestamptz,
    date_end timestamptz,

    is_current boolean not null default false,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


create table collections (
    id bigint generated by default as identity primary key,

    season_id bigint not null
        references seasons(id)
        on delete cascade,

    generated_at timestamptz,
    raw_data jsonb not null,

    created_at timestamptz not null default now(),

    unique (season_id)
);


create table api_snapshots (
    id bigint generated by default as identity primary key,

    game_version text,
    generated_at timestamptz,

    snapshot jsonb not null,

    created_at timestamptz not null default now()
);


create index idx_seasons_current
    on seasons(is_current);

create index idx_collections_season
    on collections(season_id);

create index idx_api_snapshots_created
    on api_snapshots(created_at desc);
